/**
@deprecated
**/
global with sharing class AlternateFieldConfigCtrl{
    
    global sObject sObj {get; set;}
    global String fieldApiName {get; set;}
    global SelectOption[] selectOption {get; set;}
    global String skipValue{get;set;}
    //global String selectedLabel{get;set;}
    //global String valuepicklist {get;set;}
    
    global String valuepicklist {get; set;}
    global String selectedLabel{get; set;}
    
       
}