/*
       #####################################################################################
       This Controller is used by CongaRedirect.page. This will generate a Conga URL in Apex
       and redirect to document download page.
       #####################################################################################
       08/26/2015                 Xiang               Initial version and changed hard coded Conga Ids
       04/21/2023       As discussed with Nakul deprecating this class
       #####################################################################################
*/
global with sharing class CongaRedirectCtrl {
    
    public CongaRedirectCtrl() {
    }       

}