/**
 * Created by REI on 13-06-2020.
 */

@isTest
public with sharing class DigitalSignatureCalloutMock  implements WebServiceMock{
    public void doInvoke(
        Object stub,
        Object request,
        Map<String, Object> response,
        String endpoint,
        String soapAction,
        String requestName,
        String responseNS,
        String responseName,
        String responseType){

    }
}