/**
**/
//No longer we're using this
global with sharing class DocverifyCtrl {
   
    global String AddNewDocumentESign(String apiKey,String apiSig,String Document,String DocumentName,String Emails,String MessageToSigners) {
        return null;
    }

    global String AddNewDocumentESign(String apiKey,String apiSig,String Document,String DocumentName,String Emails,String MessageToSigners, String ownerSignOrder) {
        return null;
    }

    global with sharing class DocVerify_x0020_Web_x0020_ServiceSoap {   
        
    }
}