/**
*
* 
* CHANGE HISTORY
* =============================================================================
*     Date          Name                               Description
* 29/11/2018      Chetan Dhapkale                     Created
* 15/12/2018      Chetan Dhapkale                     Main Class for Chart json data 
* 01/01/2019      Pankaj Hingane, Yogesh Sir          Code Review is Remaining
* 04/03/2019      Rahul Thange                        Modified and Enhanced
* 04/03/2019      Yogesh Gaikwad                      Reviewed
* 06/03/2019      Rahul Thange                        Changed Field API Name
* 06/03/2019      Rahul Thange                        Modified Field API Name
* 17/10/2019      Rahul Thange                        Added support for merge fields for class based
* =============================================================================
*/
 //Deprecated HighChart using Lightning Standard Charts.
 global with sharing class EnhancedChartHelper {
 
 public EnhancedChartHelper(String chartName ,String recId  ) {
 }
    

 }