/*
* CHANGE HISTORY
* =============================================================================
* Date               Name                               Description
* 28/11/2018    Chetan Dhapkale                         Created
* 01/12/2018    Chetan Dhapkale                         Wrapper Class for wrapping json data for charts
* 06/01/2019    Pankaj Hingane, Yogesh Gaikwad          Code Review is Remaining
* 04/03/2019    Rahul Thange                            Modified and Enhanced
* 04/03/2019    Yogesh Gaikwad                          Code reviewed
* 06/03/2019    Rahul Thange                            Modified Fields API name and Rewrite Code
* =============================================================================
*/

 //Deprecated HighChart using Lightning Standard Charts.
 public with sharing class EnhancedChartWrapper{

    public EnhancedChartWrapper(){}
 }