/**
* To massage the output to display exactly the way you want it to in Visualforce, Chatter helper classes.
*
* CHANGE HISTORY
*======================================================================= 
* 06/29/2014		Kunal Shah		      Created 
* 12/3/2014			William Moore		  Changed hashtag color to blue
*										  Removed <b> tags
*=======================================================================
*/

global with sharing class FeedFormatter {

    global static String formatBodyText(ConnectApi.FeedBody body) {
        String formattedText = '';
        return formattedText;
    }

    global static String formatBodyTextNew(ConnectApi.FeedBody body) {
        String formattedText = '';        
        return formattedText;
    }

}