/*
    Helper class to facilitate methods related to global search on sidebar.
    
    ****************************************************************************************
    Audit History
    ****************************************************************************************
    10-07-2018		Tomy Pallissery		Created
    11-09-2018		Tomy Pallissery		Modified - added sequence using GlobalSearchSequence__c for picklist values in global search
    ****************************************************************************************
*/
public with sharing class GlobalSearchHelper {
    public GlobalSearchHelper(){}

}