/**
   Created By   : Shambhavi Burge.
   Created Date : 03/04/2018
   Comment      : This class is created to fetch group record and redirected to flex table component.
*/
global with sharing class GroupRedirectCtrl{

    global GroupRedirectCtrl() {
    }
    
    //Method is used to redirect the page on group or queue record.
    global PageReference groupRedirect() {
        PageReference pgRef;
        return pgRef;
    }
}