/*
  This class has methods to create a HeatMap according to object name.
  **********************************************************
  Audit History
  **********************************************************
  2015-03-25  Nishit Babaria     Created
  **********************************************************  
*/

//Deprecated HighChart using Lightning Standard Charts. 
global with sharing class HeatMapBasicCtrl{
	global string chartFilterParameters{get;set;}
  public String recordId{get;set;}
	global HeatMapBasicCtrl(){

	}


}