/**
* Class to handle the Help page.
* This class will display the appropriate Help content for a given recordId.
*   
*   Inputs Expected: RecordID   
* 
* CHANGE HISTORY
* =============================================================================
* Date          Name            Description
* 02/12/2014    Kunal Shah      Created
  07/03/2014    Nakul           Updated to have variuos types of helps
* =============================================================================
*/

public with sharing class HelpCtrl {

    public HelpCtrl(ApexPages.StandardController controller) {
    
    }

}