/*
    Helper class to facilitate methods related to recently viewed.
    
    ****************************************************************************************
    Audit History
    ****************************************************************************************
    10-07-2018      Tomy Pallissery     Created
    10-08-2018      Yogeshkumar Gaikwad Added code support to Name Display Field for Recently View
    ****************************************************************************************
*/
public with sharing class RecentlyViewedHelper {
    public RecentlyViewedHelper(){}
}