/*
    Trigger Helper for ConfigPageLayoutActionTrigger.
    
    ****************************************************************************************
    Audit History
    ****************************************************************************************
    Created to test TriggerHelper.cls class Check TestTriggerHelper.cls for more information
    ****************************************************************************************
*/
public with sharing class SampleObject11TriggerHelper extends TriggerHelper{
    public void sampleMethod(){
    }
}