/**
 * Created by REI on 23-06-2020.
 */

public with sharing  class SampleBAClass  extends BusinessRuleHandlerWithLayoutHolder{

    public SampleBAClass(){

    }

    public override BusinessRuleResult execute(SObject record, DynamicLayoutHolder holder){
        BusinessRuleResult brResult;
        return brResult;
    }

    public override BusinessRuleResult execute(SObject record){
        BusinessRuleResult brResult;
        return brResult;
    }
}