/*
  This class has methods to create charts according to object name.
  **********************************************************
  Audit History
  **********************************************************
  2018-10-23  Sonali Bajirao Jadhav     Created
  **********************************************************  
*/
//Deprecated HighChart using Lightning Standard Charts. 
@isTest
private with sharing class TestChartBarStackedCtrl {

   
}