/**
    Test class for ChartsViewCtrl
    **********************************************************
    Audit History
    **********************************************************
    4/27/2014   Someone   Created
    **********************************************************  
*/
//Deprecated HighChart using Lightning Standard Charts.
@isTest
private with sharing class TestChartsViewCtrl {
   
}