@isTest
public with sharing class TestCongaRedirectCtrl {
	// public static CongaRedirectCtrl CongaRedirectObj;
	// private static void setup(){
 	// 	Account acc=TestHelper.getAccount(true);
 	// 	Test.setCurrentPageReference(new PageReference('Page.CongaFileDownload'));
	// 	System.currentPageReference().getParameters().put('id', acc.id);
	// 	ApexPages.currentPage().getParameters().put('recordId','true');
	// 	CongaRedirectObj=new CongaRedirectCtrl();
 	// }
 
	// @isTest
 	// public static void testAll(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		ApexPages.currentPage().getParameters().put('redirectType','omb');
 	// 		setup();
 	// 		Test.startTest();
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
 	// @isTest
    // public static void test_1(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		Test.startTest();
 	// 		setup();
 	// 		ApexPages.currentPage().getParameters().put('redirectType','phs');
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		CongaRedirectCtrl.isCongaInstalled();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
 	// @isTest
 	//  public static void test_2(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		Test.startTest();
 	// 		setup();
 	// 		ApexPages.currentPage().getParameters().put('redirectType','budget');
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
 	// @isTest
 	// public static void test_3(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		Test.startTest();
 	// 		setup();
 	// 		ApexPages.currentPage().getParameters().put('redirectType','coverletter');
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
 	// @isTest
 	// public static void test_4(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		Test.startTest();
 	// 		setup();
 	// 		ApexPages.currentPage().getParameters().put('redirectType','sf');
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
 	// @isTest
 	// public static void test_5(){
 	// 	user u=TestHelper.getAdminUser(true);
 	// 	system.runAs(u){
 	// 		Test.startTest();
 	// 		setup();
 	// 		ApexPages.currentPage().getParameters().put('redirectType','rr');
 	// 		Account acc=TestHelper.getAccount(true); 			
 	// 		CongaRedirectObj.congaRedirect();
 	// 		Test.stopTest();
 	// 		System.assertNotEquals(acc,null);
 	// 	}
 	// }
}