/*
This class has methods to create charts according to object name.
**********************************************************
Audit History
**********************************************************
2018-10-25  Sonali Bajirao Jadhav     Created
**********************************************************  
*/
//Deprecated HighChart using Lightning Standard Charts. 
@isTest
public with sharing class TestChartSemiCircleDonutCtrl {
   
}