/*
* CHANGE HISTORY
* =============================================================================
* Date               Name                               Description
* 03/03/2018    Rahul Thange                            Created
* 05/03/2019    Rahul Thange                            Modified and Enhanced
* 06/03/2019    Yogesh Gaikwad                          Code reviewed
* 06/03/2019    Rahul Thange                          Modified Field API Name
* =============================================================================
*/
//Deprecated HighChart using Lightning Standard Charts. 
@istest
public class TestEnhancedChartHelper {
    
}