/**
*  Test class for the MainPageTemplate
*
*  CHANGE HISTORY
*================================================================ 
*  Dated          Name              Description 
*  02/11/2014    Vinayak Sharma      Created 
* 
*
*================================================================
*/

@isTest
private with sharing class TestTabHomeCtrl {
/*
    @isTest (OnInstall=false)
    static void testMenuSideBar() {  
        TestHelper.getUserPreference(true,'ActiveAppName__c','StateAsGrantor');
        Test.startTest();
        
        TabHomeCtrl controller = new TabHomeCtrl();
        TabHomeCtrl.hideUserSideBarPreference();
        boolean hideSideBar = controller.getUserSideBarPreference();
        TabHomeCtrl.showUserSideBarPreference();
        boolean showSideBar = controller.getUserSideBarPreference();     
         
        Test.stopTest();
        
        System.assertEquals(true, hideSideBar);
        System.assertEquals(false, showSideBar);    
    
    }*/
}